artifacts:
  "@daiyam/artifact-lang-js":
    version: 0.9.3
    provides:
      - "20"
  "@daiyam/artifact-lang-ts":
    version: 0.6.3
  "@daiyam/artifact-test-mocha-ts":
    version: 0.4.2
  "@daiyam/artifact-vsx-ts":
    version: 0.8.3
  "@daiyam/artifact-vsx-zokugun":
    version: 0.3.1
  "@daiyam/artifact-vsx-bundle-ncc":
    version: 0.4.0
